package view;

import Bean.ListBean;
import Controller.ScreenSwitchController;
import java.util.ArrayList;
import java.util.List;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Student Management");
        ScreenSwitchController controller = new ScreenSwitchController(jpnView);
        controller.setView(jpnHomepage, jlbHomepage);
        List<ListBean> listItem = new ArrayList<>();
        listItem.add(new ListBean("Homepage",jpnHomepage, jlbHomepage));
        listItem.add(new ListBean("Student",jpnStudent, jlbStudent));
        listItem.add(new ListBean("Course",jpnCourse, jlbCourse));
        listItem.add(new ListBean("Class",jpnClass, jlbClass));
        listItem.add(new ListBean("Data",jpnData, jlbData));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnHomepage = new javax.swing.JPanel();
        jlbHomepage = new javax.swing.JLabel();
        jpnStudent = new javax.swing.JPanel();
        jlbStudent = new javax.swing.JLabel();
        jpnCourse = new javax.swing.JPanel();
        jlbCourse = new javax.swing.JLabel();
        jpnClass = new javax.swing.JPanel();
        jlbClass = new javax.swing.JLabel();
        jpnData = new javax.swing.JPanel();
        jlbData = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(71, 107, 107));
        jpnMenu.setAutoscrolls(true);

        jPanel4.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/app_icon_white_24dp.png"))); // NOI18N
        jLabel1.setText("Student Management");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        jpnHomepage.setBackground(new java.awt.Color(0, 107, 179));
        jpnHomepage.setPreferredSize(new java.awt.Dimension(160, 44));

        jlbHomepage.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jlbHomepage.setForeground(new java.awt.Color(255, 255, 255));
        jlbHomepage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbHomepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainScreen_white_18dp.png"))); // NOI18N
        jlbHomepage.setText("  Main Screen");

        javax.swing.GroupLayout jpnHomepageLayout = new javax.swing.GroupLayout(jpnHomepage);
        jpnHomepage.setLayout(jpnHomepageLayout);
        jpnHomepageLayout.setHorizontalGroup(
            jpnHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHomepageLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jlbHomepage, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnHomepageLayout.setVerticalGroup(
            jpnHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHomepage, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jpnStudent.setBackground(new java.awt.Color(76, 175, 80));
        jpnStudent.setPreferredSize(new java.awt.Dimension(160, 44));

        jlbStudent.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jlbStudent.setForeground(new java.awt.Color(255, 255, 255));
        jlbStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student_white_18dp.png"))); // NOI18N
        jlbStudent.setText("  Student");

        javax.swing.GroupLayout jpnStudentLayout = new javax.swing.GroupLayout(jpnStudent);
        jpnStudent.setLayout(jpnStudentLayout);
        jpnStudentLayout.setHorizontalGroup(
            jpnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnStudentLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jlbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnStudentLayout.setVerticalGroup(
            jpnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jpnCourse.setBackground(new java.awt.Color(76, 175, 80));
        jpnCourse.setPreferredSize(new java.awt.Dimension(160, 44));

        jlbCourse.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jlbCourse.setForeground(new java.awt.Color(255, 255, 255));
        jlbCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course_white_18dp.png"))); // NOI18N
        jlbCourse.setText("  Course");

        javax.swing.GroupLayout jpnCourseLayout = new javax.swing.GroupLayout(jpnCourse);
        jpnCourse.setLayout(jpnCourseLayout);
        jpnCourseLayout.setHorizontalGroup(
            jpnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCourseLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jlbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnCourseLayout.setVerticalGroup(
            jpnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jpnClass.setBackground(new java.awt.Color(76, 175, 80));
        jpnClass.setPreferredSize(new java.awt.Dimension(160, 44));

        jlbClass.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jlbClass.setForeground(new java.awt.Color(255, 255, 255));
        jlbClass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/class_white_18dp.png"))); // NOI18N
        jlbClass.setText("  Class");

        javax.swing.GroupLayout jpnClassLayout = new javax.swing.GroupLayout(jpnClass);
        jpnClass.setLayout(jpnClassLayout);
        jpnClassLayout.setHorizontalGroup(
            jpnClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnClassLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jlbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnClassLayout.setVerticalGroup(
            jpnClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbClass, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jpnData.setBackground(new java.awt.Color(76, 175, 80));
        jpnData.setPreferredSize(new java.awt.Dimension(160, 44));

        jlbData.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jlbData.setForeground(new java.awt.Color(255, 255, 255));
        jlbData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/data_white_18dp.png"))); // NOI18N
        jlbData.setText("  Data");

        javax.swing.GroupLayout jpnDataLayout = new javax.swing.GroupLayout(jpnData);
        jpnData.setLayout(jpnDataLayout);
        jpnDataLayout.setHorizontalGroup(
            jpnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDataLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jlbData, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnDataLayout.setVerticalGroup(
            jpnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnHomepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jpnHomepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jpnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jpnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jpnClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jpnData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbClass;
    private javax.swing.JLabel jlbCourse;
    private javax.swing.JLabel jlbData;
    private javax.swing.JLabel jlbHomepage;
    private javax.swing.JLabel jlbStudent;
    private javax.swing.JPanel jpnClass;
    private javax.swing.JPanel jpnCourse;
    private javax.swing.JPanel jpnData;
    private javax.swing.JPanel jpnHomepage;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnStudent;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
